###

<img src="https://raw.githubusercontent.com/PSS-code/PSS-code/output/snake.svg" alt="Snake animation" />

###

<picture>
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/PSS-code/PSS-code/output/pacman-contribution-graph.svg">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/PSS-code/PSS-code/output/pacman-contribution-graph.svg">
</picture>

###
